kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-config-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config-test
  template:
    metadata:
      labels:
        app: spring-config-test
    spec:
      containers:
        - name: spring-config-test
          image: vineethmadhu/spring-config-test:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: "{\n  \"spring\": {\n    \"application\": {\n      \"name\": \"my-spring-config-test-app\"\n    },\n    \"cloud\": {\n      \"kubernetes\": {\n        \"config\": {\n          \"name\": \"spring-config-map\",\n          \"sources\": [\n            {\n              \"name\": \"spring-config-map\"\n            }\n          ]\n        }\n      }\n    },\n    \"profiles\": {\n      \"active\": \"dev,kubernetes\"\n    }\n  }\n}"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spring-config-test
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config-map
  labels:
    app: "my-spring-config-test-app"
    component: "spring"
data:
  application.yaml: "spring:\n  application:\n    name: \"my-spring-config-test-app\"\n  main:\n    cloud-platform: kubernetes\n    allow-bean-definition-overriding: true\n  cloud:\n    kubernetes:\n      reload:\n        enabled: true\n    discovery:\n      client:\n        composite-indicator:\n          enabled: false\nmy-application:\n  items:\n    - \"Item 1\"\n    - \"Item 2\"\n    - \"Item 3\"\n    - \"Item 4\"\n    - \"Item 5\"\n---\nspring:\n  config:\n    activate:\n      on-profile: dev\n\nmy-application:\n  items:\n    - \"Item 1\"\n    - \"Item 6\"\n    - \"Item 7\""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-config-test
  labels:
    app: "spring-config-test"
    component: "spring-config-test"
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - watch
      - list
    resources:
      - configmaps
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-config-test
  labels:
    app: "spring-config-test"
    component: "spring-config-test"
subjects:
  - kind: ServiceAccount
    name: "spring-config-test"
    apiGroup: ""
roleRef:
  kind: Role
  name: "spring-config-test"
  apiGroup: ""