kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-config-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config-test
  template:
    metadata:
      labels:
        app: spring-config-test
    spec:
      containers:
        - name: spring-config-test
          image: vineethmadhu/spring-config-test:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: "{\n  \"spring\": {\n    \"application\": {\n      \"name\": \"my-spring-config-test-app\"\n    },\n    \"cloud\": {\n      \"kubernetes\": {\n        \"config\": {\n          \"name\": \"config-test\",\n          \"sources\": [\n            {\n              \"name\": \"config-test\"\n            }\n          ]\n        }\n      }\n    },\n    \"profiles\": {\n      \"active\": \"dev,kubernetes\"\n    }\n  }\n}"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spring-config-test
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config-test
  labels:
    app: "my-spring-config-test-app"
    component: "spring"
data:
  application.yaml: "spring:\n  application:\n    name: \"my-spring-config-test-app\"\n  main:\n    cloud-platform: kubernetes\n    allow-bean-definition-overriding: true\n  cloud:\n    kubernetes:\n      reload:\n        enabled: true\n    discovery:\n      client:\n        composite-indicator:\n          enabled: false\n\nmanagement:\n  endpoint:\n    health:\n      probes:\n        enabled: true\n  health:\n    livenessState:\n      enabled: true\n    readinessState:\n      enabled: true\nmy-application:\n  users:\n    - username: \"admin\"\n      password: \"password\"\n      roles:\n        - \"READ\"\n        - \"WRITE\"\n        - \"DELETE\"\n    - username: \"dev\"\n      password: \"devPassword\"\n      roles:\n        - \"READ\"\n    - username: \"staging\"\n      password: \"stagingPassword\"\n      roles:\n        - \"WRITE\"\n---\nspring:\n  profiles:\n    dev\nmy-application:\n  users:\n    - username: \"dev\"\n      password: \"devPassword\"\n      roles:\n        - \"READ\""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-config-test
  labels:
    app: "spring-config-test"
    component: "spring-config-test"
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - watch
      - list
    resources:
      - configmaps
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-config-test
  labels:
    app: "spring-config-test"
    component: "spring-config-test"
subjects:
  - kind: ServiceAccount
    name: "spring-config-test"
    apiGroup: ""
roleRef:
  kind: Role
  name: "spring-config-test"
  apiGroup: ""